core/urls.py
from django.conf.urls import patterns, include, url
from .views import *
from django.contrib.auth.decorators import login_required

urlpatterns = patterns('',
    url(r'^$', Home.as_view(), name='home'),
    url(r'^user/', include('registration.backends.simple.urls')),
    url(r'^user/', include('django.contrib.auth.urls')),
    url(r'^stock/create/$', login_required(StockPost.as_view()), name='stock_create'),
    url(r'stock/$', login_required(StockList.as_view()), name='stock_list'),
    url(r'^stock/(?P<pk>\d+)/$', login_required(StockDetail.as_view()), name='stock_detail'),
    url(r'^stock/update/(?P<pk>\d+)/$', login_required(StockUpdate.as_view()), name='stock_update'),
    url(r'^stock/delete/(?P<pk>\d+)/$', login_required(StockDelete.as_view()), name='stock_delete'),
    url(r'^stock/(?P<pk>\d+)/review/create/$', login_required(CreateReview.as_view()), name='review_create'),
    url(r'^stock/(?P<stock_pk>\d+)/review/update/(?P<review_pk>\d+)/$', login_required(UpdateReview.as_view()), name='review_update'),
    url(r'^stock/(?P<stock_pk>\d+)/review/delete/(?P<review_pk>\d+)/$', login_required(DeleteReview.as_view()), name='review_delete'),
    url(r'^vote/$', login_required(VoteFormView.as_view()), name='vote'),
    url(r'^user/(?P<slug>\w+)/$', login_required(UserDetail.as_view()), name='user_detail'),
    url(r'^user/update/(?P<slug>\w+)/$', login_required(UserEdit.as_view()), name='user_edit'),
    url(r'^user/delete/(?P<slug>\w+)/$', login_required(DeleteUser.as_view()), name='user_delete'),
    url(r'^search/$', login_required(SearchStock.as_view()), name='search'),
)

stock_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('core.urls')),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

POST_CHOICES = (
(0, 'Public'),
(1, 'Anonymous'),
)

# Create your models here.
class Stock(models.Model):
    symbol = models.CharField(max_length=300)
    company = models.CharField(max_length=300)
    description = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User)
    post = models.IntegerField(choices=POST_CHOICES, default=0)

    def __unicode__(self):
        return self.company

    def get_absolute_url(self):
        return reverse("stock_detail", args=[self.id])

class Review(models.Model):
    stock = models.ForeignKey(Stock)
    user = models.ForeignKey(User)
    created_at = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    post = models.IntegerField(choices=POST_CHOICES, default=0)

    def __unicode__(self):
        return self.text

class Vote(models.Model):
    user = models.ForeignKey(User)
    stock = models.ForeignKey(Stock, blank=True, null=True)
    review = models.ForeignKey(Review, blank=True, null=True)

    def __unicode__(self):
        return "%s upvoted" % (self.user.username)

templates/stock/stock_delete_form.html
{% extends 'base.html' %}
{% block content %}
<p class="lead">Are you sure you want to delete "{{ stock.company }}"</p>
<form method="post" action="">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Delete</button>
</form>
{% endblock %}

templates/stock/stock_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ stock.company }}</h1>
<p>{{ stock.description }}</p>
<p>Posted {% if stock.post == 0 %} by <a href="{% url 'user_detail' slug=stock.user.username %}">{{ stock.user.username }}</a> {% endif %} on {{ stock.created_at }}</p>
{% if stock.user == user %}
<p><a href="{% url 'stock_update' pk=stock.id %}">Edit Stock</a></p>
<p><a href="{% url 'stock_delete' pk=stock.id %}">Delete Stock</a></p>
{% endif %}
{% if reviews.count > 0 %}
<h3>{{ reviews.count }} Review{{ reviews.count|pluralize }}:</h3>
{% endif %}
{% for review in reviews %}
<div class="panel">
    <p>{{ review.text }}</p>
    {% if review.user == user %}
    <p><a href="{% url 'review_update' stock_pk=stock.id review_pk=review.id %}">Edit Review</a></p>
    <p><a href="{% url 'review_delete' stock_pk=stock.id review_pk=review.id %}">Delete Review</a></p>
    {% endif %}
    <p>Reviewed {% if review.post == 0 %} by <a href="{% url 'user_detail' slug=review.user.username %}">{{ review.user.username }}</a> {% endif %} on {{ review.created_at }}</p>
    <form method="post" action="{% url 'vote' %}">
        <span class="badge">{{ review.vote_set.all.count }} Vote{{  review.vote_set.all.count|pluralize }}</span>
        {% csrf_token %}
        <input type="hidden" name="review" value="{{ review.id }}" />
        <input type="hidden" name="stock" value="{{ stock.id }}" />
        <input type="hidden" name="user" value="{{ user.id }}" />
        {% if review in user_votes %}  
        <button class="btn btn-link">
            <span class="glyphicon glyphicon-thumbs-down"></span>
        </button>
        {% else %}
        <button class="btn btn-link">
            <span class="glyphicon glyphicon-thumbs-up"></span>
        </button>
        {% endif %}
    </form>
</div>
{% endfor %}
{% if not user_reviews %}
<p><a href="{% url 'review_create' pk=stock.id %}">Write Review</a></p>
{% endif %}
{% endblock %}

templates/stock/stock_form.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block content %}
<div class="row">
<div class="col-lg-6">
<form method="post" action="">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
</div>
{% endblock %}

templates/stock/stock_list.html
{% extends 'base.html' %}
{% block content %}
{% for stock in object_list %}
<div class="panel">
    <h3><a href="{{ stock.get_absolute_url }}">{{ stock.company }}</a></h3>
    <p>Posted {% if stock.post == 0 %} by <a href="{% url 'user_detail' slug=stock.user.username %}">{{ stock.user.username }}</a> {% endif %} on {{ stock.created_at }}</p>
    <form method="post" action="{% url 'vote' %}">
        <span class="badge">{{ stock.review_set.all.count }} Review{{  stock.review_set.all.count|pluralize }}</span>
        <span class="badge">{{ stock.vote_set.all.count }} Vote{{ stock.vote_set.all.count|pluralize }}</span>
        {% csrf_token %}
        <input type="hidden" name="stock" value="{{ stock.id }}" />
        <input type="hidden" name="user" value="{{ user.id }}" />
        {% if stock in user_votes %}
        <button class="btn btn-link">
            <span class="glyphicon glyphicon-thumbs-down"></span>
        </button>
        {% else %}
        <button class="btn btn-link">
            <span class="glyphicon glyphicon-thumbs-up"></span>
        </button>
        {% endif %}
    </form>
</div>
{% empty %}
<p>No results found.</p>
{% endfor %}
{% if is_paginated %}
<nav>
    <ul class="pager">
        {% if page_obj.has_previous %}
        <li><a href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li><a href="?page={{ page_obj.next_page_number }}">Next</a></li>
        {% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}